/*
 * generated by Xtext 2.10.0
 */
package com.nextcloud.idea.completion

import com.nextcloud.idea.lang.AppDSLLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class AppDSLCompletionContributor extends AbstractAppDSLCompletionContributor {
	new() {
		this(AppDSLLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
