/*
 * generated by Xtext 2.10.0
 */
package com.nextcloud.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class AppDSLIdeaModule extends AbstractAppDSLIdeaModule {
}
