/*
 * generated by Xtext 2.10.0
 */
package com.nextcloud.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class AppDSLIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new AppDSLStandaloneSetupIdea().createInjector
	}

}
