/*
 * generated by Xtext 2.10.0
 */
package com.nextcloud.idea.lang


class AppDSLFileType extends AbstractAppDSLFileType {
	public static final AppDSLFileType INSTANCE = new AppDSLFileType()
	
	new() {
		super(AppDSLLanguage.INSTANCE)
	}
}
