/*
 * generated by Xtext 2.10.0
 */
package com.nextcloud.validation

import com.nextcloud.appDSL.App
import com.nextcloud.appDSL.AppDSLPackage
import org.eclipse.xtext.validation.Check
import com.nextcloud.appDSL.Entity
import com.nextcloud.appDSL.Attribute
import com.nextcloud.appDSL.CustomAttribute
import com.nextcloud.appDSL.PredefinedAttribute
import com.nextcloud.appDSL.RefAttribute
import org.eclipse.emf.ecore.EStructuralFeature

class AppDSLValidator extends AbstractAppDSLValidator {

	public static val INVALID_APP_NAME = 'invalidName'
	public static val INVALID_ENTITY_NAME = 'invalidName'
	public static val INVALID_ATTRIBUTE_NAME = 'invalidAttributeName'
	private static val REGEX_CAMEL_CASE = "[A-Z][a-z]*([A-Z]+[a-z]*)*"

	@Check
	def checkAppNameStartsWithCapital(App app) {
		if (!app.name.matches(REGEX_CAMEL_CASE)) {
			error('App name should be camel case', AppDSLPackage.Literals.APP__NAME,
				com.nextcloud.validation.AppDSLValidator.INVALID_APP_NAME)
		}
	}

	@Check
	def checkEntityName(Entity entity) {
		if (!entity.name.matches(REGEX_CAMEL_CASE)) {
			error('Entity name is empty or not camel case', AppDSLPackage.Literals.ENTITY__NAME,
				com.nextcloud.validation.AppDSLValidator.INVALID_ENTITY_NAME)
		}
	}

	@Check
	def checkEntityAttributeNamesUniquea(Attribute attribute) {
		var parent = attribute.eContainer as Entity;
		if (parent.attributes.filter[a | a.name == attribute.name].size > 1) {
			if (attribute instanceof CustomAttribute) {
				error('Attribute is not unique', AppDSLPackage.Literals.CUSTOM_ATTRIBUTE__NAME,
					com.nextcloud.validation.AppDSLValidator.INVALID_ATTRIBUTE_NAME)
			} else if (attribute instanceof RefAttribute) {
				error('Attribute is not unique', AppDSLPackage.Literals.REF_ATTRIBUTE__REF,
					com.nextcloud.validation.AppDSLValidator.INVALID_ATTRIBUTE_NAME)
			}
		}
	}

	def getName(Attribute attribute) {
		if (attribute instanceof RefAttribute) {
			return (attribute as RefAttribute).ref.name.toLowerCase + '_id';
		} else if (attribute instanceof CustomAttribute) {
			return (attribute as CustomAttribute).name;
		}
		return '';
	}

}
